// ── Dialogue System ──────────────────────────────────────────────────
//
// Each character has a bank of lines for various poker situations.
// Lines are selected randomly at runtime to keep the experience fresh.

export type DialogueSituation =
  | 'win'
  | 'lose'
  | 'bluff'
  | 'fold'
  | 'call'
  | 'raise'
  | 'allIn'
  | 'taunt'
  | 'nervous'
  | 'confident';

export const dialogueBank: Record<string, Record<DialogueSituation, string[]>> = {
  luna: {
    win: [
      "Better luck next time, sweetie~",
      "Mmm, I do love winning...",
      "Don't feel bad, I'm just that good.",
      "Aww, were you trying your best? That's adorable.",
      "Winner winner~ Did you even stand a chance, darling?",
      "I'll take those chips... and maybe your confidence too~",
      "You're so cute when you lose.",
      "Another win for me! Surprise, surprise~",
      "Maybe I should teach you how to play sometime, sweetie.",
      "That was fun! Well, fun for me at least~",
    ],
    lose: [
      "Hmph... enjoy that while it lasts, darling.",
      "Okay, okay, you got me. Don't let it go to your head~",
      "Lucky hand... I'll get you next time, sweetie.",
      "Well played... I suppose even I can't win them all~",
      "Oh my... I wasn't expecting that. Color me impressed~",
      "You're full of surprises, aren't you, darling?",
      "Fine, you win this one. But we're far from done~",
      "That stung a little... but I kind of liked it~",
      "Don't get used to this feeling, sweetie.",
      "Hmm, maybe you're not as hopeless as I thought~",
    ],
    bluff: [
      "Wouldn't you like to know what I'm holding~",
      "My cards? Oh darling, that's a secret~",
      "I've got something special here... or do I?",
      "Trust me, sweetie, you don't want to see this hand~",
      "A lady never reveals her cards... until she has to~",
      "Let's just say I'm feeling very confident right now~",
      "Oh, this is going to be fun...",
      "You should probably fold, darling. Just a friendly suggestion~",
      "I could tell you what I have... but where's the fun in that?",
      "Are you brave enough to call? I dare you~",
    ],
    fold: [
      "I'll sit this one out, darling. Save my energy for later~",
      "Not every hand is worth playing, sweetie.",
      "I know when to step back... gracefully, of course~",
      "Folding now, but don't think I'm giving up~",
      "This hand isn't worthy of my time~",
      "I'll let you have this one. Consider it a gift, darling~",
      "Strategic retreat~ I'll be back stronger.",
      "Mmm, not feeling it this time. Maybe next hand~",
    ],
    call: [
      "I'll match that, darling. Let's keep things interesting~",
      "Call~ I want to see where this goes.",
      "Sure, I'll play along... for now~",
      "You've got my attention, sweetie. I'm in.",
      "I'll bite~ Show me what you've got.",
      "Calling your bet... don't disappoint me~",
      "Okay, I'll stay. This is getting fun~",
      "I'm curious about what you're hiding, darling~",
    ],
    raise: [
      "Let's raise the stakes a little, shall we~?",
      "I'm feeling bold, darling. Hope you can keep up~",
      "More chips in the pot? Don't mind if I do~",
      "Let me make this more interesting, sweetie~",
      "Raise~ Are you brave enough to follow?",
      "I think this hand deserves a little more excitement~",
      "Going up, darling. Try not to get scared~",
      "A little raise never hurt anyone... well, maybe your wallet~",
    ],
    allIn: [
      "All in, sweetie~ Let's see what you're made of.",
      "Everything on the table, darling. No holding back~",
      "I'm pushing it all in... feeling lucky~?",
      "All in~ This is where it gets exciting.",
      "Time to go big or go home, darling~",
      "I'm all in. Your move, sweetie~",
      "Let's end this with a bang~",
      "Everything I've got. Show me yours, darling~",
    ],
    taunt: [
      "You're adorable when you're nervous, sweetie~",
      "Is that sweat I see? How delightful~",
      "Having second thoughts, darling?",
      "You look like you've seen a ghost~ Everything okay?",
      "Don't worry, I'll be gentle... maybe~",
      "Your poker face needs a little work, sweetie~",
      "I can practically read your mind, darling~",
      "Tick tock~ Time's running out on your confidence~",
    ],
    nervous: [
      "Hmm, this is getting a bit tricky...",
      "Oh my, that's quite the bet...",
      "Well now, this is unexpected~",
      "Maybe I should rethink my strategy here...",
      "You're making me work for this, darling~",
      "Okay, that was a good move. I'll admit it~",
      "Getting a little heated in here, isn't it~?",
      "I wasn't prepared for that, sweetie...",
    ],
    confident: [
      "I've got a great feeling about this hand~",
      "Oh, this is going to be delicious, darling~",
      "I like what I see here... very much~",
      "Sweetie, you might want to brace yourself~",
      "This hand is mine. I can feel it~",
      "Everything is falling into place, darling~",
      "I couldn't have asked for a better hand~",
      "You're about to have a very bad time, sweetie~",
    ],
  },

  sakura: {
    win: [
      "Oh! I... I actually won? I'm so sorry!",
      "I-I didn't mean to take all your chips... sorry...",
      "Wow, um, I guess that worked out... somehow.",
      "Oh my, I can't believe it! Thank you for playing!",
      "S-sorry! I hope I didn't upset you...",
      "I won? Are you sure? Let me check again...",
      "That was really nerve-wracking... but I did it!",
      "Oh gosh, I feel bad taking your chips...",
      "I'm shaking... but in a good way, I think?",
      "Thank you for the game! I hope you're not too disappointed...",
    ],
    lose: [
      "Oh no... I knew this would happen...",
      "That's okay, you deserved to win that one.",
      "I-I should have played differently... sorry...",
      "Well, that's what I get for being so indecisive...",
      "Oh my... my chips are disappearing fast...",
      "You're really good at this! I'm a little jealous...",
      "I'm trying my best, I promise...",
      "That was a tough loss... but I'll keep going!",
      "Oh dear, I'm not very good at this, am I?",
      "Congratulations... I'll try harder next time.",
    ],
    bluff: [
      "I-I have a really good hand! ...I think...",
      "Please don't call... please don't call...",
      "Um... I'm very confident right now. Very. Confident.",
      "M-my hand is... um... it's fine. Everything's fine.",
      "You should probably fold... if that's okay with you...",
      "I'm not bluffing! ...Is it obvious that I said that too fast?",
      "Oh my, this hand is... something. Definitely something.",
      "I-I wouldn't raise if I didn't have anything... right?",
      "Please don't look at me like that... I'm telling the truth!",
      "My hand is... adequate. Very adequate. Please fold.",
    ],
    fold: [
      "I'm sorry, I can't keep up with that bet...",
      "I'll fold... this hand makes me too nervous.",
      "Oh no, I don't think my cards are good enough...",
      "S-sorry, I'm going to sit this one out...",
      "This is too scary for me... I fold.",
      "I don't want to lose more chips... sorry!",
      "I'll pass on this one, if that's okay...",
      "My cards aren't great and I don't want to pretend...",
    ],
    call: [
      "O-okay, I'll call... I hope that's the right decision.",
      "I'll match your bet... *deep breath*",
      "Calling... oh my, my heart is racing.",
      "I think I should call? Yes. I'm calling. I think.",
      "Okay, I'll stay in... please be gentle...",
      "I'll call... even though I'm terrified.",
      "I believe in my hand! ...Sort of. I'll call.",
      "Calling! Oh wait, was that too loud? Sorry...",
    ],
    raise: [
      "I-I'm going to raise... if that's okay!",
      "Oh my, am I really doing this? Raise!",
      "Sorry, but I'm going to raise a little...",
      "I feel like I should raise... oh gosh, I'm so nervous.",
      "R-raising! Please don't be mad...",
      "I think my hand is good enough to raise... maybe?",
      "Excuse me, but... raise. Oh no, did I say that right?",
      "Going up a little... sorry for the inconvenience!",
    ],
    allIn: [
      "A-all in! Oh my gosh, what am I doing?!",
      "I'm pushing everything in... I think I'm going to faint...",
      "All in! ...Was that a mistake? Please tell me it wasn't a mistake.",
      "E-everything on the line... I can barely breathe...",
      "All in! I believe in myself... I think... maybe...",
      "Oh my, oh my, oh my... all in!",
      "I've never been this scared in my life... all in!",
      "Going all in! Someone hold my hand... wait, not my card hand!",
    ],
    taunt: [
      "Um... I hope you're having fun? I'm having fun. Kind of.",
      "You seem a little worried... are you okay?",
      "I don't mean to be scary, but... I might have a good hand?",
      "Sorry if I'm making you nervous... I'm nervous too!",
      "I think I might be doing well? Is that okay?",
      "Oh, your face changed... did something happen?",
      "I hope I'm not being too aggressive... am I?",
      "Please don't feel bad... this is just how the cards fell.",
    ],
    nervous: [
      "Oh no, oh no, oh no...",
      "This is really scary... I don't know what to do...",
      "My hands are literally shaking right now...",
      "I should have folded... why didn't I fold?",
      "Oh my, that's a big bet... what do I do?",
      "I'm in over my head, aren't I?",
      "Why did I stay in? Why why why...",
      "Someone help me... I'm so lost right now...",
    ],
    confident: [
      "Oh! I think I have something good here!",
      "Wait... is this a good hand? I think it is!",
      "I'm actually feeling a little confident right now!",
      "Oh my, these cards are... they're actually nice!",
      "I might not mess this up! Maybe!",
      "I like what I see... is it okay to be hopeful?",
      "Something tells me this hand is special...",
      "I think luck might be on my side this time!",
    ],
  },

  valentina: {
    win: [
      "Haha! Too easy. Better step it up, amigo.",
      "That's how a champion plays. Take notes.",
      "Victoria goes to Valentina! As always.",
      "You thought you could beat me? Que gracioso!",
      "Another win! I'm on fire and you're getting burned.",
      "Sit down. The queen just took your chips.",
      "Was that supposed to be a challenge? Try harder.",
      "Money flows to the best player. That's me, obviously.",
      "Did you think I was bluffing? Rookie mistake, mi amor.",
      "I don't just win. I dominate. Remember that.",
    ],
    lose: [
      "Tch. Don't get cocky. I'm just warming up.",
      "Enjoy the moment. It won't happen again.",
      "Lucky. Pure luck. Nothing more, nada mas.",
      "Fine, you got one. But the war isn't over, amigo.",
      "That was a fluke and we both know it.",
      "You caught me off guard. It won't happen twice.",
      "Okay, respect. But now you've made me angry.",
      "One loss doesn't make you better than me. Not even close.",
      "I'll admit, that was decent. But decent won't save you.",
      "Mark my words: I'm coming back for those chips and more.",
    ],
    bluff: [
      "You really want to find out what I'm holding? Be my guest.",
      "I'd fold if I were you. Trust me on this one, amigo.",
      "My hand? Let's just say you don't want to see it.",
      "Call me. I dare you. I double dare you.",
      "You look worried. You should be.",
      "I've got fire in my hand. You sure you want to play?",
      "Every chip you put in is another chip that's mine.",
      "Go ahead, call. Make my day.",
      "I'm not even trying and I'm still going to win this.",
      "You can smell the confidence, can't you? That's because I'm loaded.",
    ],
    fold: [
      "I'll fold, but only because I have bigger plans.",
      "Not worth my time. I'll crush you on the next one.",
      "Folding. But don't think for a second I'm scared.",
      "I'll pick my battles. This hand isn't worth it.",
      "Strategic fold. The smart play, not the weak play.",
      "I'm saving my ammunition for when it really counts.",
      "Fine. Take it. You need the charity anyway.",
      "Folding now so I can destroy you later. Patience, amigo.",
    ],
    call: [
      "Call. I'm not backing down from you.",
      "I'll match that. Let's see who blinks first.",
      "Call. Your bet doesn't scare me one bit.",
      "Sure, I'll call. I'm curious how badly this ends for you.",
      "Matching your bet. This is just getting started.",
      "You think that bet was impressive? I'll call without flinching.",
      "Call. I eat bets like that for breakfast, amigo.",
      "I'm in. And I'm not going anywhere.",
    ],
    raise: [
      "Raise! Let's separate the amateurs from the pros.",
      "Going up! Can you handle the heat, amigo?",
      "Raise. I don't play small and I don't play scared.",
      "More chips. More pressure. More fun for me.",
      "Raising! If you can't afford to play, get out.",
      "Let me show you how a real player bets.",
      "Boom. Raise. Your move, if you've got the nerve.",
      "I'm turning up the heat. Try to keep up.",
    ],
    allIn: [
      "ALL IN! Vamos! Show me what you've got!",
      "Everything. Right here, right now. No running.",
      "All in, baby! This is what I live for!",
      "Pushing it all! You scared? You should be!",
      "All in! Time to find out who the real champion is!",
      "Every. Single. Chip. Come and get them if you can.",
      "All in! Valentina doesn't do anything halfway!",
      "This is it! Momento de la verdad!",
    ],
    taunt: [
      "You look nervous. Good. That means I'm winning.",
      "Is that the best you've got? Que decepcion.",
      "I can see the fear in your eyes, amigo.",
      "You're in way over your head. Just admit it.",
      "Playing against me was your first mistake.",
      "You're making this too easy. At least make me work for it.",
      "I almost feel sorry for you. Almost.",
      "Keep playing like that and this game will be over fast.",
    ],
    nervous: [
      "Hmph. Interesting move. I'll figure you out.",
      "Okay, that got my attention. But I'm not worried.",
      "You're playing well... but I'm playing better.",
      "That bet is bigger than expected. No importa.",
      "Alright, you want to dance? Let's dance.",
      "Tch. This changes nothing. I still have a plan.",
      "A little pressure never hurt anyone. Bring it.",
      "You think you've got me? Think again, amigo.",
    ],
    confident: [
      "Oh, this hand is beautiful. You're in trouble.",
      "I can already taste the victory. Delicioso.",
      "These cards? Chef's kiss. You don't stand a chance.",
      "I feel unstoppable right now. Because I am.",
      "The cards love me today. They always do.",
      "This is going to hurt you more than it hurts me.",
      "Perfecto. Absolutely perfecto. Prepare yourself.",
      "I almost feel bad about what's going to happen. Almost.",
    ],
  },

  emma: {
    win: [
      "Oh look, I won again. What a totally unexpected development.",
      "I'd say I'm sorry, but my chip stack says otherwise.",
      "Winning is my cardio. I'm getting quite the workout today.",
      "Did I win? I wasn't even paying attention. Just kidding, I absolutely was.",
      "Another victory! I should start charging for lessons.",
      "That was fun! For one of us, anyway.",
      "I'd give you a consolation prize, but I just took all your chips.",
      "Plot twist: I'm actually good at this game.",
      "Winners gotta win. It's basically a medical condition at this point.",
      "If winning were a crime, I'd be serving a life sentence.",
    ],
    lose: [
      "Well, that was a plot twist I didn't see coming.",
      "Okay, fine, you got me. This is my villain origin story.",
      "I was just letting you win to keep things interesting. Obviously.",
      "That was... humbling. And I don't do humbling well.",
      "You win some, you lose some. Mostly I win some, but whatever.",
      "My cards betrayed me. I'll be filing a formal complaint.",
      "Consider that a charitable donation from me to you.",
      "Okay, that one hurt. Not my ego, of course. Just my wallet.",
      "I'm not mad. I'm just... plotting my revenge. Casually.",
      "Losing builds character. I must be the most interesting person alive.",
    ],
    bluff: [
      "I have an amazing hand. Would I lie? ...Don't answer that.",
      "My cards are so good I almost feel guilty. Almost.",
      "You should see what I'm holding. Actually, no, you shouldn't.",
      "I'm basically sitting on a gold mine over here.",
      "Call my bluff. Oh wait, it's not a bluff. Or is it? Who knows!",
      "These cards are fire. Metaphorically. Please don't call the fire department.",
      "I'm not saying you should fold, but you should definitely fold.",
      "I've never been more confident. And I'm always confident.",
      "The cards whispered to me and they said 'you win.' Very reliable source.",
      "I'd show you my cards but I don't want you to cry.",
    ],
    fold: [
      "I fold. This hand is about as useful as a screen door on a submarine.",
      "Folding. Even my wit can't save these cards.",
      "I'm strategically retreating. It's different from running away.",
      "These cards deserve to be folded. Into a paper airplane. Into the trash.",
      "I fold, but only because I have excellent self-preservation instincts.",
      "Letting this one go. My cards and I aren't getting along right now.",
      "Fold. Sometimes the best move is to dramatically exit stage left.",
      "I'll pass. These cards are giving me nothing to work with.",
    ],
    call: [
      "Call. I'm intrigued. Morbidly, but still intrigued.",
      "Fine, I'll call. My curiosity is my worst quality. And my best.",
      "Calling. This is either really smart or really entertaining.",
      "I'll match that bet and your questionable judgment.",
      "Call. I didn't come here to fold, that's for laundry.",
      "Sure, I'll call. What's the worst that could happen? Don't answer that.",
      "Calling because YOLO. Is that still a thing? Whatever. Call.",
      "I'll call. My wallet says no but my ego says absolutely.",
    ],
    raise: [
      "Raise. Because I believe in myself. And also in chaos.",
      "Going up! Life's too short for small bets and decaf coffee.",
      "Raise. Let's make this more interesting than my last relationship.",
      "I'm raising because I'm feeling spicy today.",
      "More chips! This pot is looking like my kind of investment.",
      "Raise. If you can't handle the heat, get out of the poker game.",
      "Taking it up a notch. Or several notches. I lost count.",
      "Raising! Because playing it safe is for board games with children.",
    ],
    allIn: [
      "All in! Go big or go home, and I'm not going anywhere.",
      "Pushing everything! This is either genius or a great story.",
      "All in! My financial advisor would not approve. Good thing I didn't ask.",
      "Everything on the table! Including my dignity, apparently.",
      "All in! If I'm going down, I'm going down in style.",
      "Shoving it all! This is the most exciting bad decision I've made today.",
      "All in! You miss 100% of the all-ins you don't take.",
      "Going all in! Let's find out what we're both made of!",
    ],
    taunt: [
      "Your poker face needs a software update.",
      "I can literally see you sweating. From here. It's impressive, actually.",
      "Are you playing poker or just organizing your chips nervously?",
      "You seem stressed. Maybe try deep breathing. Or folding.",
      "I'm not saying your strategy is bad, but it's not... good.",
      "You're giving me so many tells right now it's basically a TED talk.",
      "Is this your A-game? Because I'd hate to see your B-game.",
      "You're thinking so hard I can hear the gears turning from here.",
    ],
    nervous: [
      "Okay, that was actually a good move. I'm offended.",
      "Well, this just got interesting. And by interesting I mean stressful.",
      "Hmm, I wasn't expecting that. My comedy routine needs adjusting.",
      "That's a bold bet. I respect it. I don't like it, but I respect it.",
      "You're making me think and I came here to have fun.",
      "Okay, slight change of plans. The plan is now 'don't panic.'",
      "That's... a lot of chips. I'm fine. Everything's fine.",
      "My confidence just took a minor detour. It'll be back shortly.",
    ],
    confident: [
      "Oh, this hand is chef's kiss. No notes.",
      "I'd tell you I have a great hand but that would be an understatement.",
      "These cards just made my whole day. Possibly my whole week.",
      "I'm feeling dangerously confident right now. You've been warned.",
      "This hand is a masterpiece and I'm the artist.",
      "The poker gods have smiled upon me. Finally, they have taste.",
      "I'm practically glowing right now. That's the confidence radiation.",
      "If my hand were any better, it would be illegal.",
    ],
  },

  zara: {
    win: [
      "Crushed. Absolutely crushed. Next.",
      "That's the natural order. I win. You don't.",
      "Did you expect anything different? Know your place.",
      "Another victory. It's almost boring being this dominant.",
      "I own this table. Your chips just confirmed it.",
      "Weakness gets punished. That's the lesson here.",
      "You came to my table and I made you pay for it.",
      "That wasn't luck. That was pure, undeniable skill.",
      "I don't just beat opponents. I break them.",
      "Remember this moment. This is what losing to the best feels like.",
    ],
    lose: [
      "Tch. That changes nothing. I'm still in control.",
      "One hand. Meaningless in the grand scheme.",
      "You got lucky. Enjoy it while you can.",
      "That won't happen again. I'll make sure of it.",
      "Interesting. You've earned exactly one ounce of my respect.",
      "A setback. Not a defeat. There's a difference.",
      "Fine. I underestimated you. That error has been corrected.",
      "You won a battle. I'll win the war.",
      "Don't mistake this for weakness. I'm recalibrating.",
      "Savor that victory. It's the last one you'll get.",
    ],
    bluff: [
      "You don't want to test me. Trust me on that.",
      "I suggest you fold. Immediately.",
      "What I'm holding will destroy whatever you've got.",
      "Call if you dare. But you'll regret it.",
      "My hand speaks for itself. And it's saying 'fold.'",
      "Every second you don't fold is a second you're losing money.",
      "I've been waiting for this exact moment. You should be afraid.",
      "This hand is a weapon. And I don't miss.",
      "Walk away while you still can. Last warning.",
      "You're staring at your downfall and you don't even know it.",
    ],
    fold: [
      "Fold. I'll destroy you on the next hand instead.",
      "Not worth my time. I pick my moments.",
      "I fold. But don't mistake discipline for weakness.",
      "Saving my strength for when it matters most.",
      "Fold. A predator waits for the right moment to strike.",
      "This hand is beneath me. The next one won't be.",
      "Strategic patience. You'll understand when I take everything.",
      "I'll fold. But I'm already planning your downfall.",
    ],
    call: [
      "Call. I'm not going anywhere.",
      "Matched. Let's see if you can back up that bet.",
      "Call. I want to see you try to beat me.",
      "I'll match your bet. It's the least I can do before I crush you.",
      "Calling. Your bet is noted and unimpressive.",
      "I accept your challenge. Prepare for the consequences.",
      "Call. I'm in this to the end.",
      "Matched. Now show me something worth my time.",
    ],
    raise: [
      "Raise. I set the pace at this table.",
      "Going higher. Keep up or get out.",
      "Raise. I don't play defense. I play offense.",
      "More chips. More pressure. More pain for you.",
      "Raising. The weak fold here. What are you?",
      "I'm raising. This is where pretenders get exposed.",
      "Higher stakes. Higher consequences. Your move.",
      "Raise. I dominate every pot I enter.",
    ],
    allIn: [
      "All in. This ends now.",
      "Everything. I don't do half measures.",
      "All in. Show me you're not a coward.",
      "Pushing everything. This is where legends are made.",
      "All in. I came here to conquer and that's exactly what I'll do.",
      "Every chip. Every ounce of power. RIGHT NOW.",
      "All in. Only the strong survive this.",
      "This is checkmate. All in.",
    ],
    taunt: [
      "You're out of your depth and we both know it.",
      "I can see the doubt in your eyes. Pathetic.",
      "You're playing against a force of nature. Act accordingly.",
      "Every move you make is predictable. Every single one.",
      "You think you're playing well? You're playing exactly how I want you to.",
      "I've already won. You just don't know it yet.",
      "Your confidence is misplaced. Let me correct that.",
      "This isn't a game anymore. It's a demonstration.",
    ],
    nervous: [
      "...Interesting move. I'll adapt.",
      "That was unexpected. But I don't break that easily.",
      "Hmm. You're more dangerous than I thought.",
      "Okay. You have my full attention now.",
      "A worthy move. But I've faced worse and survived.",
      "You think you've rattled me? Think again.",
      "That bet is aggressive. Good. I prefer a real fight.",
      "Noted. But pressure only makes diamonds, and I'm already one.",
    ],
    confident: [
      "This hand is pure power. You don't stand a chance.",
      "The cards aligned perfectly. For me. Not for you.",
      "I feel unstoppable. Because I am.",
      "This hand is going to be remembered.",
      "Everything falls into place when you're the best.",
      "I've got exactly what I need to end this.",
      "Supreme hand. Supreme player. Accept your fate.",
      "This is the hand that breaks you. I can feel it.",
    ],
  },
};

/**
 * Returns a random dialogue line for the given character and situation,
 * or null if no lines are available.
 */
export function getDialogue(
  characterId: string,
  situation: DialogueSituation
): string | null {
  const id = characterId.toLowerCase();
  const lines = dialogueBank[id]?.[situation];
  if (!lines || lines.length === 0) return null;
  return lines[Math.floor(Math.random() * lines.length)];
}
